name: 'aws-codepipeline-trigger'
description: 'Trigger an AWS CodePipeline from GitHub Actions'
inputs:
  pipeline-name:
    description: 'The name of the CodePipeline'
    required: true
  wait:
    description: 'Wait for the CodePipeline to finish and exit with same result as the CodePipeline'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
